name: "Godot GUT test"

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rainbowcow-studio/godot-tester@feature/node-20
      with:
        # required
        version: "4.1"
        # the type of release of godot that the tests should be run with
        release_type: "stable"
        is-mono: "false"
        # the folder with your project.godot file in it
        path: "./"
        # how long to spend importing assets before tests are run
        import-time: "5"
        # how long tests can run in seconds
        test-timeout: "45"
        # the ratio of tests that must pass for this action to pass
        # e.g. 0.6 means 60% of your tests must pass
        minimum-pass: "1"
        # the directory containing Gut tests
        test-dir: "res://test"
        # not checked by default, set to a number to limit the
        # maximum amount of failed tests for a passing test suite
        max-fails: 1
